name: Lint checking

on:
  pull_request:
    branches:
      - main

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Run flake8 linting

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run flake8 lint
        uses: py-actions/flake8@v2.3.0
        with:
          max-line-length: "200"
